#pragma once

/* Taster auf Tasterplatine */
#define COLUMN_PORT PORTC
#define ROW_PORT    PORTC
#define COL1_PIN  PIN7_bm
#define COL2_PIN  PIN6_bm
#define COL3_PIN  PIN4_bm
#define COL4_PIN  PIN2_bm
#define COL5_PIN  PIN0_bm
#define ROW1_PIN  PIN5_bm
#define ROW2_PIN  PIN3_bm
#define ROW3_PIN  PIN1_bm

#define COL1SETUP COLUMN_PORT.DIRCLR=COL1_PIN; COLUMN_PORT.PIN7CTRL = PORT_SRLEN_bm | PORT_OPC_PULLUP_gc | PORT_ISC_FALLING_gc
#define COL1_OFF  COLUMN_PORT.OUTCLR=COL1_PIN
#define COL1_ON   COLUMN_PORT.OUTSET=COL1_PIN
#define COL1_TOGGLE  COLUMN_PORT.OUTTGL=COL1_PIN

#define COL2SETUP COLUMN_PORT.DIRCLR=COL2_PIN; COLUMN_PORT.PIN6CTRL = PORT_SRLEN_bm | PORT_OPC_PULLUP_gc | PORT_ISC_FALLING_gc
#define COL2_OFF  COLUMN_PORT.OUTCLR=COL2_PIN
#define COL2_ON   COLUMN_PORT.OUTSET=COL2_PIN
#define COL2_TOGGLE  COLUMN_PORT.OUTTGL=COL2_PIN

#define COL3SETUP COLUMN_PORT.DIRCLR=COL3_PIN; COLUMN_PORT.PIN4CTRL = PORT_SRLEN_bm | PORT_OPC_PULLUP_gc | PORT_ISC_FALLING_gc
#define COL3_OFF  COLUMN_PORT.OUTCLR=COL3_PIN
#define COL3_ON   COLUMN_PORT.OUTSET=COL3_PIN
#define COL3_TOGGLE  COLUMN_PORT.OUTTGL=COL3_PIN

#define COL4SETUP COLUMN_PORT.DIRCLR=COL4_PIN; COLUMN_PORT.PIN2CTRL = PORT_SRLEN_bm | PORT_OPC_PULLUP_gc | PORT_ISC_FALLING_gc
#define COL4_OFF  COLUMN_PORT.OUTCLR=COL4_PIN
#define COL4_ON   COLUMN_PORT.OUTSET=COL4_PIN
#define COL4_TOGGLE  COLUMN_PORT.OUTTGL=COL4_PIN

#define COL5SETUP COLUMN_PORT.DIRCLR=COL5_PIN; COLUMN_PORT.PIN0CTRL = PORT_SRLEN_bm | PORT_OPC_PULLUP_gc | PORT_ISC_FALLING_gc
#define COL5_OFF  COLUMN_PORT.OUTCLR=COL5_PIN
#define COL5_ON   COLUMN_PORT.OUTSET=COL5_PIN
#define COL5_TOGGLE  COLUMN_PORT.OUTTGL=COL5_PIN

#define ROW1SETUP ROW_PORT.DIRSET=ROW1_PIN; ROW_PORT.OUTCLR=ROW1_PIN
#define ROW1_OFF  ROW_PORT.OUTCLR=ROW1_PIN
#define ROW1_ON   ROW_PORT.OUTSET=ROW1_PIN
#define ROW1_TOGGLE  ROW_PORT.OUTTGL=ROW1_PIN

#define ROW2SETUP ROW_PORT.DIRSET=ROW2_PIN; ROW_PORT.OUTCLR=ROW2_PIN
#define ROW2_OFF  ROW_PORT.OUTCLR=ROW2_PIN
#define ROW2_ON   ROW_PORT.OUTSET=ROW2_PIN
#define ROW2_TOGGLE  ROW_PORT.OUTTGL=ROW2_PIN

#define ROW3SETUP ROW_PORT.DIRSET=ROW3_PIN; ROW_PORT.OUTCLR=ROW3_PIN
#define ROW3_OFF  ROW_PORT.OUTCLR=ROW3_PIN
#define ROW3_ON   ROW_PORT.OUTSET=ROW3_PIN
#define ROW3_TOGGLE  ROW_PORT.OUTTGL=ROW3_PIN

